name: Upload coverage reports to Codecov
on:
  push:
    branches:
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests and collect coverage
        run: pytest --cov .
      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}